# Execute via Kaimon in the coutellier_agripv project.
include("plant_balance.jl")
include("simulation_outputs.jl")
include("mtg_outputs.jl")
include("scene.jl")
include("geometry_selector.jl")
include("saved_simulation.jl")
include("fvcb.jl")
include("year_simulation.jl")
include("year_fapar.jl")
